### ISSUE TITLE
completely transparent elements in discord canary

### ISSUE THREAD

**Issue by eylles** [Gremious/discord-wal-theme-template#5]
great template, i really love the use of the pywalfox formula to create the additional shades, however i'm experiencing this issue of some elements like tooltips and the popup menus being completely transparent

![image](https://github.com/Gremious/discord-wal-theme-template/assets/33670677/0d98d5c2-b342-47e0-9a1d-ee6d6dd93398)

i'm using pywal16, discord canary, the pywal template and injecting the css with [beautifuldiscord](https://github.com/leovoel/BeautifulDiscord)

**Comment by Gremious** [comment]
Sorry I took ages to get to this!

I ran canary + beautiful discord on Windows but my pop-up menus are still  totally fine..

I don't have a linux machine rn to test, could you be bothered to do a quick check for me please?

I've attached a video to show it better, but if you could:
1. Open the chrome debug menu (ctrl+shift+i)
2. Click the select element button on the top left side of the console
3. And then just click on a pop-up menu (not on an item, the outer ele) (it's 3 nested ones, the middle one, has "role=menu" for me)

Could you tell me the name of the background var? For me it's `--background-floating`. Maybe it's different on your build.

You can also test it right then and there, if you want. If you change it to e.g. `red` instead of `var(--background-floating)` it should make that menu red. Would be good to know if that'd work.

https://github.com/Gremious/discord-wal-theme-template/assets/21365711/695f7ec7-b41c-4c13-8759-7c094d1432e4

**Comment by eylles** [comment]
welp got some feed back... but first of all good news it ain't an issue anymore!

it seems that for whatever reason on discord-canary versions 0.0.315 to 0.0.335 on linux cannot use vars like `$bg` 


![image](https://github.com/Gremious/discord-wal-theme-template/assets/33670677/bb0ebd0b-36a1-4743-8cc1-4da8a330b6f7)

![image](https://github.com/Gremious/discord-wal-theme-template/assets/33670677/0f9112b9-7fd9-40c8-9dd0-d775c7e661b6)

![image](https://github.com/Gremious/discord-wal-theme-template/assets/33670677/c6124ba9-17db-48d6-a94b-4b85e21b07ad)


however it just works on version 0.0.349 also just works on discord 0.0.49

![image](https://github.com/Gremious/discord-wal-theme-template/assets/33670677/44bb67f6-e652-4e31-9552-e8c77642676d)

so this is just something dumb that happened on canary for about 20+ versions...

**Comment by Gremious** [comment]
I love software
